name: where_to_go
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  flutter: 3.32.7
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_hooks: ^0.21.3+1
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  flutter_riverpod: ^2.6.1
  go_router: ^16.2.0
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  dio: ^5.9.0
  flutter_secure_storage: ^4.2.1
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  freezed_annotation: ^3.1.0
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: 2.5.4
  flutter_gen_runner: ^5.11.0
  custom_lint: ^0.7.6
  riverpod_lint: ^2.6.5
  riverpod_generator: ^2.6.5
  solvro_config: ^1.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
