name: where_to_go
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  flutter: 3.32.7
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_hooks: ^0.21.3+1
  flutter_riverpod: ^2.4.9
  hooks_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  go_router: ^16.2.0
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  solvro_config: ^1.0.1
  build_runner: ^2.5.4
  flutter_gen_runner: ^5.3.2
  custom_lint: ^0.7.1
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  drift_dev: ^2.28.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
