name: dream_places
description: A Flutter app with Riverpod and GoRouter.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: "3.32.7"

dependencies:
  flutter:
    sdk: flutter

  # Riverpod do zarządzania stanem
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # GoRouter do nawigacji
  go_router: ^14.2.0

  # Obsługa wygenerowanych assetów
  flutter_gen: ^5.5.0

  # Dodatkowe zależności z drugiego pliku
  cupertino_icons: ^1.0.8
  flutter_hooks: ^0.21.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  #generator kodu dla Riverpoda
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.5

  solvro_config: ^1.0.1
  flutter_gen_runner: ^5.11.0

flutter_gen:
  output: lib/gen/
  line_length: 80

flutter:
  uses-material-design: true

  assets:
    - assets/images/